modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Tassis"
description='''Field notes for Draconic Evolution, with optional Patchouli, JEI, and Jade integrations.'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="draconicevolution"
type="required"
versionRange="[3.1.4.633]"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jei"
type="optional"
versionRange="[19.51.0.418]"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="jade"
type="optional"
versionRange="[15.10.6,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="patchouli"
type="optional"
versionRange="[1.21.1-93,)"
ordering="AFTER"
side="BOTH"
